### ISSUE TITLE
Meta table dlng and slng fields should list script tags not language tags

### ISSUE THREAD

**Issue by babelstone** [unicode-org/last-resort-font#10]
The meta table dlng and slng fields each give a comma-separated list of language tags (ca,cs,cy,da,de,en,es,fi,fr,hr,hu,id,is,it,lt,ms,mt,nb,nl,nn,pl,pt,ro,sk,sv,tr,vi for dlng; and 240 language tags for slng). However the [specification for the meta table](https://docs.microsoft.com/en-us/typography/opentype/otspec181/meta) states that ScriptLangTag values use a modification of the BCP 47 syntax: a script subtag is mandatory and other subtags are optional. It further states that "it is anticipated that most tags used in 'dlng' and 'slng' metadata declarations will consist only of a script subtag".

Therefore, the lists of language tags should be changed to use lists of script tags (e.g. Latn, Cyrl, Hani, etc.).

**Comment by rickmcgowan** [comment]
My crystal ball says the 'meta' table will be removed when the fonts are updated for Version 15.0 later this year.

**Comment by Tsengtsz** [comment]
Fixed in version 15.000.
