### ISSUE TITLE
Incorrect ranges

### ISSUE THREAD

**Issue by RebeccaRGB** [unicode-org/last-resort-font#11]
A few of the last resort glyphs have incorrect values for the range of the block they represent:

lastresortmathoperatorssup: should be 2A00..2AFF, but shows 2AA0..2AFF.
lastresortcjkextf: should be 2CEB0..2EBEF, but shows 2B820..2CEAF.
lastresortvariationselectorsa: should be E0100..E01EF, but shows E0110..E01FF.

**Comment by rickmcgowan** [comment]
The glyphs will be fixed for the update for Unicode Version 15.0.

**Comment by Tsengtsz** [comment]
Fixed in version 15.000.
