### ISSUE TITLE
Sources and scripts upstream? 

### ISSUE THREAD

**Issue by BrianInglis** [unicode-org/last-resort-font#15]
Where can we get the upstream sources and scripts to re-/build the font if we want to make our own updates available before official releases?

**Comment by kenlunde** [comment]
The repository’s landing page (aka _README.md_ file) includes the following statement:
> NOTE: _The sources and build scripts may be added after Unicode Version 15.1.0 has been released (2023), and as time and resources permit._

**Comment by BrianInglis** [comment]
Why the long delay in just adding the font and tool sources? 
The project should at least contain links to the upstream font glyph sources and build tools sources, otherwise the font is not truly open source, as it can not be easily reproduced from its sources and tools, and rebuilt from scratch. 
It makes me uncomfortable to distribute fonts, which we can not promptly modify and rebuild ourselves, should something happen to your project, sources, or selves.

**Comment by kenlunde** [comment]
The process to add new glyphs (for new blocks in the Unicode Standard) and to update the fonts is really quite involved, so part of the delay is to produce clear documentation. Also, and at a very practical level, the fonts are specifically designed to be in sync with the latest version of the Unicode Standard, so there is really no need for contributions. Besides, for the vast majority of people who use these fonts, the open source license simply means that the fonts are completely free to use.

We can consider doing what you are requesting piecemeal, such as to forego the documentation for updating the fonts, such as adding new glyphs, and instead to add the sources, tools, and documentation to simply rebuild the current version of the fonts from source. We can consider doing this as part of the [Unicode Version 16.0](https://www.unicode.org/versions/Unicode16.0.0/) release later this year.

**Comment by BrianInglis** [comment]
Thanks, that would be great if you could manage that much. 
When at least the basic bits are available, downstream maintainers feel that, if anything happens to the upstream project, designer, or developers, or they just lack sufficient free time, those who have time and interest could contribute to keep the product up to date. 
[I have contributed to projects, where you wondered how core maintainers found the time to do as much as they did in their lives and for the project, then life or org stuff happened, free time was occupied, they had to resign, and a large gap in knowledge, experience, effort, and time was left, which can only be slowly filled by others in, and coming into the project, and picking up the pieces.]

**Comment by alerque** [comment]
If the the scripts and tools necessary to build a project are not available, the sources are incomplete. It doesn't do much good to have partial sources available if they can't be made use of by anyone outside of the maintainer(s).

**Comment by BrianInglis** [comment]
There are also issues developing with TrueType font support: some projects have stated that the format and/or hinting are so broken that they will in future support higher quality renderings only of OpenType fonts. 
So some font projects are dropping or have dropped TrueType fonts, and provide only OpenType fonts. 
We are also noticing that OpenType fonts can be more compact than the TrueType fonts with the same repertoire, so there may be less pressure to provide WOFF fonts, although those are useful for browsers, as WebP and WebM are more compact for images and videos from the web.

**Comment by kenlunde** [comment]
@BrianInglis For fonts such as the ones in this repository, the arguments in favor of OpenType/CFF do not hold much water. And yes, I have a couple dozen years of experience developing OpenType/CFF fonts as a profession, so I have strong biases in that direction. (The build process actually produces OpenType/CFF versions of the fonts, but the build script also torpedoes them, along with other temporary files. So, once I add the sources, scripts, and build process, you will be free to build your own OpenType/CFF versions by modifying the build script.) We will therefore continue to provide TrueType versions of the fonts, and may add WOFFs and WOFF2s as new assets in the next release.

**Comment by BrianInglis** [comment]
It appears that there may be platform dependent pros and cons, but if the most popular high quality font rendering library developers are saying *poo* to TrueType, and reserving their efforts for OpenType; and font packages are dropping TrueType, and building and installing only OpenType, unless the distro package maintainer jumps through unsupported hoops for the build and install, downstreams have to take note and make appropriate plans. 
Luckily *MacOS* and *Windows* font support appears to be filling in their gaps to handle more options in fonts, so there are fewer ignored tables, entries, hints, and visible rendering defects.

**Comment by kenlunde** [comment]
To follow up on this, I updated the fonts for Unicode Version 16.0 this morning, and I am planning to release the update on 2024-09-10, which is the same date when [Unicode Version 16.0](https://www.unicode.org/versions/Unicode16.0.0/) is expected to be released. I am also planning to add to the repository as part of that release the sources and build scripts.

**Comment by BrianInglis** [comment]
@kenlunde Thanks Ken, Looking forward to seeing those updates and tools.

**Comment by khaledhosny** [comment]
> but if the most popular high quality font rendering library developers are saying _poo_ to TrueType

Just curious, what library is that and where this is said?

**Comment by BrianInglis** [comment]
Not getting into that, but for example, look at how *Truetype* is labelled *Legacy font technologies* at [MS Typography](https://learn.microsoft.com/en-us/typography/)! 
Newer font rendering libraries are ignoring more font hints in favour of their own alternative approaches, and OpenType supports more alternative glyph tables for Swash, Small Caps, Old Style Non-Lining and Tabular Digits and other characters, Ligatures, non-LGC positional forms, Language and Script variants, Math positioning forms, Direction Mirroring, Colours, and glyph runs for character blocks, etc.

**Comment by khaledhosny** [comment]
I was specifically curious to know what “most popular high quality font rendering library developers are saying poo to TrueType”.

**Comment by kenlunde** [comment]
Well, the original TrueType format is certainly legacy, but modern TrueType fonts are actually OpenType fonts that include a 'glyf' table for their outlines. In any case, the default deployment format shall continue to be TrueType-flavor OpenType fonts.

**Comment by kenlunde** [comment]
For those who did not get the memo, the sources and build scripts were added in the [Latest Release](https://github.com/unicode-org/last-resort-font/releases/latest/) that was issued yesterday.
