### ISSUE TITLE
C

### ISSUE THREAD

**Issue by Szercinek12** [unicode-org/last-resort-font#2]

**Comment by alerque** [comment]
I'm going to go out on a limb and suggest this issue report is somewhat incomplete.

Ç

**Comment by kenmcd** [comment]
Appears to be some sort of spammer strategy.
Create user, fork a bunch of projects, fork projects from other similar fake users to link them together, then post nonsense issue posts like above to add more incoming links. 
Have not yet followed them far enough to figure-out the end game.
So this "issue" appears to be spam.
