### ISSUE TITLE
Problem with font priority

### ISSUE THREAD

**Issue by ismail** [unicode-org/last-resort-font#3]
(This is not a font bug per se, but I run into this using openSUSE Tumbleweed, so it might be good to document for future)

After installing last-resort-font on my system I noticed that Chrome and many other apps (except xterm for some reason) started to render 𝐳 (U+1D433) character using last-resort-font, this can be confirmed with:

```
sisyphus ~ > fc-list ':charset=1D433'
/usr/share/fonts/truetype/STIXGeneral-Regular.otf: STIXGeneral:style=Regular
/usr/share/fonts/winfonts/cambria.ttc: Cambria:style=Regular
/usr/share/fonts/truetype/LastResortHE-Regular.ttf: Last Resort High\-Efficiency:style=Regular <--- HERE
/usr/share/fonts/truetype/STIXGeneral-Bold.otf: STIXGeneral:style=Bold
/usr/share/fonts/truetype/DejaVuSerifCondensed-Bold.ttf: DejaVu Serif,DejaVu Serif Condensed:style=CondensedBold,Bold
/usr/share/fonts/truetype/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/winfonts/cambria.ttc: Cambria Math:style=Regular
/usr/share/fonts/truetype/DejaVuMathTeXGyre.ttf: DejaVu Math TeX Gyre:style=Regular
```

So, it's matching last-resort-font before looking up other fonts where the glyph actually exists. I looked up in the fontconfig documentation, but I couldn't find a way to decrease a font's priority to be last. If you have any ideas, it'd be appreciated.

**Comment by alerque** [comment]
I haven't been able to solve this on Arch Linux either. The fallback works great for those code points that don't exist anywhere, but I can't figure out how to force fontconfig to prioritize it last behind other possible fallback fonts that might have real glyphs.

**Comment by rickmcgowan** [comment]
Because this is not an issue with the font, this issue is being closed.
