### ISSUE TITLE
Change representative glyph of CJK Unified Ideographs Extension G to U+30EDE 𰻞

### ISSUE THREAD

**Issue by NightFurySL2001** [unicode-org/last-resort-font#5]
Random suggestion: U+30EDE (𰻞) is a well-known glyph for its "most" stroke count and complexity, and also the name for [a type of noodles in China](https://en.wikipedia.org/wiki/Biangbiang_noodles), and most people that are in the field already knows the location of this character. Using U+30EDE as the representative glyph is a good indication for CJK Ext-G, which can be taken from Source Han Serif.
![image](https://user-images.githubusercontent.com/33471049/153616719-93881ed8-a1ed-42e7-844a-18a67e619813.png)

**Comment by rickmcgowan** [comment]
Thank you for your input. Unless the representative glyph for a particular block is incorrect, it will not be changed.
