### ISSUE TITLE
High-Efficiency font has an invalid Platform/Encoding/Format combination

### ISSUE THREAD

**Issue by babelstone** [unicode-org/last-resort-font#8]
The Last Resort High-Efficiency font has an invalid Platform/Encoding/Format combination. According to the [OpenType specification](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap) "Encoding ID 6 should only be used in conjunction with 'cmap' subtable format 13; and subtable format 13 should only be used under platform ID 0 and encoding ID 6". However the LRHE font has subtable format 13 under Encoding ID 10 (Unicode Full Repertoire) and Platform ID 3 (Windows). The font should be changed to have subtable format 13 under Encoding ID 6 (Unicode Full Repertoire) and Platform ID 0 (Unicode).

**Comment by rickmcgowan** [comment]
Thank you for the report. This is scheduled to be fixed in the update for Unicode Version 15.0

**Comment by Tsengtsz** [comment]
Fixed in version 15.000.
