### ISSUE TITLE
Last Resort font displays the notdef glyph for BMP characters under Windows 10

### ISSUE THREAD

**Issue by babelstone** [unicode-org/last-resort-font#9]
The Last Resort font has two cmap tables: a Format 4 subtable (Encoding ID 1 and Platform ID 3) with zero characters defined; and a Format 10 subtable (Encoding ID 10 and Platform ID 3) covering 1,114,112 characters.

When tested with Notepad under Windows 10, characters in the BMP are displayed with the notdef glyph because Windows uses the Format 4 subtable for the BMP. All characters outside the BMP are displayed correctly because the Format 10 subtable is used for supra-BMP characters. See attached screenshot for Notepad displaying two BMP characters and one character each from Planes 1-3, using the Last Resort font.

Possible solutions would be to A) remove the empty Format 4 subtable; or B) make the Format 4 subtable functional for all characters in the BMP.

NB This issue should also affect the High-Efficiency font.

![LastResort_BMP_test](https://user-images.githubusercontent.com/20558386/180668905-3e41592a-27c0-4edc-b193-d6d19deb04e0.png)
.

**Comment by rickmcgowan** [comment]
Thank you for the report. This is scheduled to be fixed in the update for Unicode Version 15.0

**Comment by Tsengtsz** [comment]
Fixed in version 15.000.

**Comment by SBVels** [comment]
Hi. What new now
